version: "3.8"

services:
  app:
    build: .
    network_mode: "host"
    volumes:
      - .:/app
    depends_on:
      - db
    env_file:
      - .env

  db: 
    image: postgres:latest
    environment:
      POSTGRES_PASSWORD: pgdbpass
      POSTGRES_USER: pgdbuser
    ports: 
      - "5432:5432"
    restart: always
